/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理端登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录请求 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 用户名 */
                        username: string;
                        /** @description 密码 */
                        password: string;
                        /** @description 验证码token */
                        captchaToken: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 访问令牌 */
                                accessToken: string;
                            };
                        };
                    };
                };
                /** @description 验证码错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 密码错误 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 用户被禁用 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 用户不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理端刷新访问令牌 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刷新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 访问令牌 */
                                accessToken: string;
                            };
                        };
                    };
                };
                /** @description 刷新令牌无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理端退出登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 退出成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: Record<string, never>;
                        };
                    };
                };
                /** @description 未授权 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 管理端获取当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /**
                                 * Format: uuid
                                 * @description 用户ID
                                 */
                                id: string;
                                /** @description 用户名 */
                                username: string;
                                /** @description 头像 */
                                avatar: string | null;
                                /** @description 昵称 */
                                nickName: string;
                                /** @description 用户角色 */
                                roles: string[];
                            };
                        };
                    };
                };
                /** @description 用户不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 管理端获取当前用户权限 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 权限列表 */
                                permissions: string[];
                            };
                        };
                    };
                };
                /** @description 角色不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理端生成验证码挑战 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 生成成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 验证码挑战数据 */
                            challenge?: unknown;
                            /** @description 挑战token */
                            token?: string;
                            /** @description 过期时间戳 */
                            expires: number;
                        };
                    };
                };
                /** @description 生成失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理端验证用户解答 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 验证请求 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 挑战token */
                        token: string;
                        /** @description 用户解答 */
                        solutions: number[];
                    };
                };
            };
            responses: {
                /** @description 验证成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 验证结果 */
                            success: boolean;
                            /** @description 验证token */
                            token?: string;
                            /** @description 过期时间戳 */
                            expires?: number;
                        };
                    };
                };
                /** @description 验证失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/resources/object-storage/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OS-获取上传预签名 URL
         * @description 用于管理员上传文件到对象存储
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 上传令牌请求 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 文件名 */
                        fileName: string;
                        /** @description 文件类型 */
                        fileType?: string;
                    };
                };
            };
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 预签名 URL */
                                url: string;
                                /** @description 过期时间 */
                                expiresAt: string;
                            };
                        };
                    };
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 参数验证失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success: boolean;
                            /**
                             * @example {
                             *       "name": "ZodError",
                             *       "issues": [
                             *         {
                             *           "code": "invalid_type",
                             *           "path": [
                             *             "fileName"
                             *           ],
                             *           "message": "Invalid input: expected string, received undefined"
                             *         }
                             *       ]
                             *     }
                             */
                            error: {
                                issues: {
                                    code: string;
                                    path: (string | number)[];
                                    message?: string;
                                }[];
                                name: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/resources/object-storage/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OS-获取下载预签名 URL
         * @description 用于管理员从对象存储下载文件
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 下载令牌请求 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 文件名 */
                        fileName: string;
                    };
                };
            };
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 预签名 URL */
                                url: string;
                                /** @description 过期时间 */
                                expiresAt: string;
                            };
                        };
                    };
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 参数验证失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success: boolean;
                            /**
                             * @example {
                             *       "name": "ZodError",
                             *       "issues": [
                             *         {
                             *           "code": "invalid_type",
                             *           "path": [
                             *             "fileName"
                             *           ],
                             *           "message": "Invalid input: expected string, received undefined"
                             *         }
                             *       ]
                             *     }
                             */
                            error: {
                                issues: {
                                    code: string;
                                    path: (string | number)[];
                                    message?: string;
                                }[];
                                name: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统角色列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 当前页码 */
                    current?: number;
                    /** @description 每页大小 */
                    pageSize?: number;
                    /** @description 分页模式：server=服务端分页，client=客户端分页，off=不分页 */
                    mode?: PathsApiAdminSystemRolesGetParametersQueryMode;
                    /** @description 过滤条件，JSON 字符串格式 */
                    filters?: string;
                    /** @description 排序条件，JSON 字符串格式 */
                    sorters?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 列表响应成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 角色ID */
                                id: string;
                                createdAt: string | null;
                                createdBy: string | null;
                                updatedAt: string | null;
                                updatedBy: string | null;
                                /** @description 角色名称 */
                                name: string;
                                /** @description 角色描述 */
                                description: string | null;
                                /**
                                 * @description 状态 (ENABLED=启用, DISABLED=禁用)
                                 * @enum {string}
                                 */
                                status: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                            }[];
                        };
                    };
                };
                /** @description 查询参数验证错误 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 服务器内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建系统角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 创建系统角色参数 */
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        description?: string | null;
                        /** @enum {string} */
                        status?: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                    };
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 角色ID */
                                id: string;
                                createdAt: string | null;
                                createdBy: string | null;
                                updatedAt: string | null;
                                updatedBy: string | null;
                                /** @description 角色名称 */
                                name: string;
                                /** @description 角色描述 */
                                description: string | null;
                                /**
                                 * @description 状态 (ENABLED=启用, DISABLED=禁用)
                                 * @enum {string}
                                 */
                                status: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                            };
                        };
                    };
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 角色代码已存在 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 参数验证失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统角色详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 角色ID */
                                id: string;
                                createdAt: string | null;
                                createdBy: string | null;
                                updatedAt: string | null;
                                updatedBy: string | null;
                                /** @description 角色名称 */
                                name: string;
                                /** @description 角色描述 */
                                description: string | null;
                                /**
                                 * @description 状态 (ENABLED=启用, DISABLED=禁用)
                                 * @enum {string}
                                 */
                                status: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                            };
                        };
                    };
                };
                /** @description ID参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 角色不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除系统角色 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 角色ID */
                                id: string;
                            };
                        };
                    };
                };
                /** @description ID参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 角色不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 更新系统角色 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 更新系统角色参数 */
            requestBody: {
                content: {
                    "application/json": {
                        id?: string;
                        name?: string;
                        description?: string | null;
                        /** @enum {string} */
                        status?: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 角色ID */
                                id: string;
                                createdAt: string | null;
                                createdBy: string | null;
                                updatedAt: string | null;
                                updatedBy: string | null;
                                /** @description 角色名称 */
                                name: string;
                                /** @description 角色描述 */
                                description: string | null;
                                /**
                                 * @description 状态 (ENABLED=启用, DISABLED=禁用)
                                 * @enum {string}
                                 */
                                status: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                            };
                        };
                    };
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 角色不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/system/roles/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取角色权限 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取权限成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: string[][];
                        };
                    };
                };
                /** @description ID参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 获取权限失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        /** 保存角色权限（全量更新） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 角色ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 保存权限参数 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 权限列表（全量） */
                        permissions: [
                            string,
                            string
                        ][];
                    };
                };
            };
            responses: {
                /** @description 保存权限成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 新增权限数量 */
                                added: number;
                                /** @description 删除权限数量 */
                                removed: number;
                                /** @description 总权限数量 */
                                total: number;
                            };
                        };
                    };
                };
                /** @description 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 角色不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 保存权限失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统用户详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 获取成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /**
                                 * Format: uuid
                                 * @description 用户ID
                                 */
                                id: string;
                                createdAt: string | null;
                                createdBy: string | null;
                                updatedAt: string | null;
                                updatedBy: string | null;
                                /** @description 用户名 */
                                username: string;
                                /** @description 是否内置用户 */
                                builtIn: boolean | null;
                                /** @description 头像 */
                                avatar: string | null;
                                /** @description 昵称 */
                                nickName: string;
                                /**
                                 * @description 状态 (ENABLED=启用, DISABLED=禁用)
                                 * @enum {string}
                                 */
                                status: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                                /** @description 用户角色 */
                                roles: {
                                    /** @description 角色ID */
                                    id: string;
                                    /** @description 角色名称 */
                                    name: string;
                                }[];
                            };
                        };
                    };
                };
                /** @description ID参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 用户不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除系统用户 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /**
                                 * Format: uuid
                                 * @example 4651e634-a530-4484-9b09-9616a28f35e3
                                 */
                                id: string;
                            };
                        };
                    };
                };
                /** @description ID参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 内置用户不允许删除 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 用户不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** 更新系统用户 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description 更新系统用户参数 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 用户名 */
                        username?: string;
                        /** @description 密码 */
                        password?: string;
                        avatar?: string | null;
                        /** @description 昵称 */
                        nickName?: string;
                        /** @enum {string} */
                        status?: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /**
                                 * Format: uuid
                                 * @description 用户ID
                                 */
                                id: string;
                                createdAt: string | null;
                                createdBy: string | null;
                                updatedAt: string | null;
                                updatedBy: string | null;
                                /** @description 用户名 */
                                username: string;
                                /** @description 是否内置用户 */
                                builtIn: boolean | null;
                                /** @description 头像 */
                                avatar: string | null;
                                /** @description 昵称 */
                                nickName: string;
                                /**
                                 * @description 状态 (ENABLED=启用, DISABLED=禁用)
                                 * @enum {string}
                                 */
                                status: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                            };
                        };
                    };
                };
                /** @description 请求参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 内置用户不允许修改状态 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 用户不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/system/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取系统用户列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 当前页码 */
                    current?: number;
                    /** @description 每页大小 */
                    pageSize?: number;
                    /** @description 分页模式：server=服务端分页，client=客户端分页，off=不分页 */
                    mode?: PathsApiAdminSystemRolesGetParametersQueryMode;
                    /** @description 过滤条件，JSON 字符串格式 */
                    filters?: string;
                    /** @description 排序条件，JSON 字符串格式 */
                    sorters?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 列表响应成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /**
                                 * Format: uuid
                                 * @description 用户ID
                                 */
                                id: string;
                                createdAt: string | null;
                                createdBy: string | null;
                                updatedAt: string | null;
                                updatedBy: string | null;
                                /** @description 用户名 */
                                username: string;
                                /** @description 是否内置用户 */
                                builtIn: boolean | null;
                                /** @description 头像 */
                                avatar: string | null;
                                /** @description 昵称 */
                                nickName: string;
                                /**
                                 * @description 状态 (ENABLED=启用, DISABLED=禁用)
                                 * @enum {string}
                                 */
                                status: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                                /** @description 用户角色 */
                                roles: {
                                    /** @description 角色ID */
                                    id: string;
                                    /** @description 角色名称 */
                                    name: string;
                                }[];
                            }[];
                        };
                    };
                };
                /** @description 查询参数验证错误 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 服务器内部错误 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建系统用户 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 创建系统用户参数 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 用户名 */
                        username: string;
                        /** @description 密码 */
                        password: string;
                        avatar?: string | null;
                        /** @description 昵称 */
                        nickName: string;
                        /** @enum {string} */
                        status?: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                    };
                };
            };
            responses: {
                /** @description 创建成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /**
                                 * Format: uuid
                                 * @description 用户ID
                                 */
                                id: string;
                                createdAt: string | null;
                                createdBy: string | null;
                                updatedAt: string | null;
                                updatedBy: string | null;
                                /** @description 用户名 */
                                username: string;
                                /** @description 是否内置用户 */
                                builtIn: boolean | null;
                                /** @description 头像 */
                                avatar: string | null;
                                /** @description 昵称 */
                                nickName: string;
                                /**
                                 * @description 状态 (ENABLED=启用, DISABLED=禁用)
                                 * @enum {string}
                                 */
                                status: PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus;
                            };
                        };
                    };
                };
                /** @description 用户名已存在 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description The validation error(s) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/system/users/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 保存用户角色（全量更新） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 用户ID */
                    userId: string;
                };
                cookie?: never;
            };
            /** @description 保存角色参数 */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 角色列表（全量） */
                        roleIds: string[];
                    };
                };
            };
            responses: {
                /** @description 保存成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description 新增角色数量 */
                                added: number;
                                /** @description 删除角色数量 */
                                removed: number;
                                /** @description 总角色数量 */
                                total: number;
                            };
                        };
                    };
                };
                /** @description 用户或角色不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description The validation error(s) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
                /** @description 保存角色失败 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 错误信息 */
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum PathsApiAdminSystemRolesGetParametersQueryMode {
    server = "server",
    client = "client",
    off = "off"
}
export enum PathsApiAdminSystemRolesGetResponses200ContentApplicationJsonDataStatus {
    ENABLED = "ENABLED",
    DISABLED = "DISABLED"
}
export type operations = Record<string, never>;
